### ISSUE TITLE
Unable to load weather data. 

### ISSUE THREAD

**Issue by linusrg1** [fajtak/ulauncher-weather#2]
Do I need a custom api. I tried my home city in canada, I even tried a more well known city like NYC with no luck.

**Comment by fajtak** [comment]
You just need your personall API key since the API is not public in the case of OpenWeatherMap. You have to register and generate your own key (it can take about few hours to activate the key) and then copy it to the extension settings tab. Here is the link to OpenWeatherMap where you can find link for registration and how-to generate yourpersonall API key.

**Comment by fajtak** [comment]
https://openweathermap.org/appid

**Comment by fajtak** [comment]
Let me know if it works for you.

**Comment by fajtak** [comment]
Ok, I hope it helped. If not, let me know.
